language: java

jdk:
  - oraclejdk8
  - oraclejdk9

after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp codacy-coverage-reporter-assembly-<version>.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml
